config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"
  post "/login" => "sessions#create", as: :login
  get "/login" => "sessions#new"
  delete "/logout" => "sessions#destroy"
  resources :users
  delete "/users/:id" => "users#destroy", as: :delete_user
  resources :photos
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  field :title, type: String
  mount_uploader :image, AvatarUploader

  belongs_to :user
end

app/models/session.rb
class Session
  include Mongoid::Document
end

app/models/user.rb
class User
  include Mongoid::Document
  field :username, type: String  
  field :email, type: String
  field :password_digest, type: String
  field :image_description, type: String
  field :title, type: String


  has_many :photos
  
  #password validation
  attr_reader :password

  # encrypts password
	def password=(unencrypted_password)
		unless unencrypted_password.empty?
	    # use BCrypt to encrypt our plain password into a digest
	    # and store it in our database
	    # create password instance variable
	    @password = unencrypted_password
	    self.password_digest = BCrypt::Password.create(unencrypted_password)
	  end
	end




	def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end

  	# user must enter username, email, password
	
      validates :username, presence: true, uniqueness: true, on: :create
      validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
      validates :password, presence: true, confirmation: true, length: { in: 6..20 }, on: :create
      validates :password, presence: true, confirmation: true, length: { in: 6..20 }, :allow_blank => true, :on => :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    include SessionsHelper
    helper_method :current_user, :login_user

    def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

    end

    def login_user(user)
	 session[:user_id] = user.id.to_s
  
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    # @photos = Photo.all
  end

  def new
    # @photo = Photo.new
    @photo = current_user.photos.new
     @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def create
    @photo = current_user.photos.new(photo_params)
    if @photo.save
      redirect_to users_path, notice: 'Photo uploaded' 
    else
      render :new
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.new
    @photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo = current_photo.destroy
    session.delete(:photo_id)
    redirect_to user_path
  end

  private
  def photo_params
    params.require(:photo).permit(:image, :title)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	   @user = User.where(username: params[:login][:username]).first
                if @user && @user.authenticate(params[:login][:password])
    	       session[:user_id] = @user.id.to_s
                    redirect_to users_path
                else
     	      redirect_to login_path
         end
      end

	def destroy
	   session.delete(:user_id)
         redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
		@photos = Photo.all
	end

	def new 
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
		session[:user_id] = @user.id.to_s
		
		redirect_to edit_user_path(@user)
	else
		render :new, alert: "Try again, hombre!"
	end
end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
		

	end

	def update 
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else 
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user = current_user.destroy
		session.delete(:user_id)
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:title, :username, :email, :password, :password_confirmation)

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper

 
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user ||= User.find(session)[:user_id]
	end

  def logged_in?
    session[:user_id] !=nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whippersnaps</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/nav'  %>
<%= yield %>

</body>
</html>

app/views/shared/_nav.html.erb
<% @user = current_user %>

<!-- Static navbar -->
      <nav class="navbar navbar-default">
            <ul class="nav navbar-nav">
           <% if logged_in? %>
              <li><%= link_to "My Profile", edit_user_path(@user) %></li>
              <li><%= link_to "Snap Pool", users_path%></li>
               <li> <%= link_to "Sign Out", logout_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Sign Up", new_user_path%></li>
              <li><%= link_to "Wait, I'm A User!", root_path  %></li>
          <% end %>
            </ul>
      </nav>

app/views/shared/_update.html.erb
<%= form_for @user do |f| %>
<%= f.label "username" %>
<%= f.text_field :username, placeholder: "username" %>
<br>
<%= f.label "email" %>
<%= f.text_field :email, placeholder: "email" %>
<%= f.submit :class => "btn btn-warning" %>

<% end %>

app/views/users/edit.html.erb
<h1>Hi, <%= @user.username %></h1>


<div class="col-md-5">
        <h2>You're one of us, it's time for you to add some Snaps! So we can admire your glory! :)</h2>

<div class="row">
    <div class="col-md-5">
      <% @user.photos.each do |photo| %>

      <%= image_tag photo.image.url(:full)%>

   <% end %>




   </div>
  </div>
</div>



<%= form_for(Photo.new) do |f| %>


  <%= f.file_field :image %>
  
<%= f.text_field :title, placeholder: "ABOUT THIS SNAP" %>
<br>
  <%= f.submit 'add snaps!!' %>
  <br>

 

  <%= link_to "OOPS It's A NUDE!! (remove SNAP)", photo_path, method: :delete %>

<br>
 <%= link_to "I hate this site!", delete_user_path(@user), method: :delete %>
  <% end %>

  <!-- Modal -->

  <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#myModal">Edit Profile
</button>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Things Change!</h4>
      </div>
      <div class="modal-body">
          <%= render 'shared/update', object: @user  %>
      </div>
      <div class="modal-body">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
   
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
    <div class="row">
            <div class="col-md-3">
                
                <div class="col-md-6">
                <% @users.each do |u| %>
                <%= link_to u.username, user_path(u)%>
</div>
            <% end %>

            </div>
    </div>
      
  <div class="row">
        <div class="col-md-3">
          <%= @photos.each do |p| %>
          <%= image_tag p.image.url(:full) %>
          <%= p.title %>
        <% end %>


        </div>
  </div>



          
        
        <!-- <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p> -->
      <!--   </div> -->

      <%= debug(params) %>

app/views/users/new.html.erb
 <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<%= form_for @user do |f| %>

     <div class="row">
          <div class=" col-md-4 col-md-offset-3 text-center ">
              <h1>Sign Up!</h1>

            
            	<%= f.text_field :username, placeholder: "username", class: "form-control text-center" %>
            	<br>
            	<%= f.text_field :email, placeholder: "email", class: "form-control text-center"%>
            	<br>
            	<%= f.password_field :password, placeholder: "password", class: "form-control text-center" %>
                  <br>
                  <%= f.password_field :password_confirmation, :placeholder => "confirm password", class: "form-control text-center"%>
                  <br>
	            <%= f.submit "submit", class: "btn btn-success"%>
           

                <% end %>
          </div>
      </div>

app/views/users/show.html.erb
<div class="row">
  <div class= "col-md-3">
<% @user.photos.each do |photo| %>

<%= image_tag photo.image.url(:full)%>

<% end %>

</div>
</div>

<%= debug(params) %>